name: Sync ALL CPI Packages to GitHub

on:
  workflow_dispatch:
  schedule:
    - cron: "30 14 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    container:
      image: engswee/flashpipe:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync ALL CPI artifacts using FlashPipe
        uses: engswee/flashpipe-action/sync@v1
        with:
          tmn-host: ${{ secrets.DEV_TMN_HOST }}
          oauth-host: ${{ secrets.DEV_OAUTH_HOST }}
          oauth-clientid: ${{ secrets.DEV_CLIENT_ID }}
          oauth-clientsecret: ${{ secrets.DEV_CLIENT_SECRET }}
          package-id: Demo

          dir-artifacts-relative: cpi-all-artifacts
          sync-package-details: true
          git-commit-msg: "Auto-sync ALL CPI packages from tenant"
