name: Deploy iFlows back to CPI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: engswee/flashpipe:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy iFlows to CPI
        uses: engswee/flashpipe-action/deploy@v1
        with:
          tmn-host: ${{ secrets.DEV_TMN_HOST }}
          oauth-host: ${{ secrets.DEV_OAUTH_HOST }}
          oauth-clientid: ${{ secrets.DEV_CLIENT_ID }}
          oauth-clientsecret: ${{ secrets.DEV_CLIENT_SECRET }}

          # Folder in GitHub containing all iFlows
          dir-artifacts-relative: cpi-all-artifacts

          # Deploy ALL packages & iFlows
          deploy-all: true

          # Automatically deploy after upload
          deploy: true

          git-commit-msg: "Deploying all iFlows to CPI"
